services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    # expose:
    #  - "6379"
  web:
    build: .
    command: gunicorn pathfinder.wsgi:application --workers=3 --bind 0.0.0.0:8000 --timeout 120
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A pathfinder worker --beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
