services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - internal
  web:
    build: .
    command: gunicorn pathfinder.wsgi:application --workers=5 --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - internal
  celery:
    build: .
    command: celery -A pathfinder worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
      - internal
  networks:
    internal:
      driver: bridge
