# Generated by Django 3.2.25 on 2024-07-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0002_auto_20240704_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
