# Generated by Django 3.2.25 on 2024-07-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0003_auto_20240707_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='url',
            field=models.URLField(max_length=1500),
        ),
    ]
