# Generated by Django 3.2.25 on 2024-07-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0004_alter_flight_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together=set(),
        ),
    ]
