# Generated by Django 3.2.25 on 2024-07-13 09:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flightfinder', '0006_alter_airport_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachePath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_caches', to='flightfinder.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_caches', to='flightfinder.airport')),
            ],
            options={
                'unique_together': {('origin', 'destination')},
            },
        ),
    ]
