ABUJA = [
    {"name": "ABJ", "airlines": []},
    {
        "name": "LOS",
        "airlines": [
            "air_peace",
            "arik_air",
            "green_africa",
            "ibom_air",
            "max_air",
            "ng_eagle",
            "rano_air",
            "united_nigeria",
            "value_jet",
        ],
    },
    {"name": "ACC", "airlines": ["air_peace"]},
    {"name": "AKR", "airlines": ["air_peace", "green_africa"]},
    {"name": "ANA", "airlines": ["air_peace", "united_nigeria"]},
    {"name": "ABB", "airlines": ["air_peace", "united_nigeria"]},
    {"name": "BJL", "airlines": ["air_peace"]},
    {"name": "BCU", "airlines": ["value_jet"]},
    {"name": "BNI", "airlines": ["air_peace", "green_africa", "united_nigeria"]},
    {"name": "DNBK", "airlines": ["max_air", "ng_eagle"]},
    {"name": "CBQ", "airlines": ["air_peace", "ibom_air"]},
    {"name": "COO", "airlines": []},
    {"name": "DSS", "airlines": ["air_peace"]},
    {"name": "DLA", "airlines": ["air_peace"]},
    {"name": "FNA", "airlines": ["air_peace"]},
    {
        "name": "ENU",
        "airlines": ["air_peace", "green_africa", "ibom_air", "united_nigeria"],
    },
    {"name": "GMO", "airlines": ["air_peace"]},
    {"name": "IBA", "airlines": ["air_peace", "green_africa"]},
    {"name": "ILR", "airlines": ["air_peace", "green_africa"]},
    {"name": "JED", "airlines": []},
    {"name": "JOS", "airlines": ["value_jet"]},
    {"name": "JNB", "airlines": ["air_peace"]},
    {"name": "KAN", "airlines": ["air_peace", "max_air", "rano_air"]},
    {"name": "KAD", "airlines": ["max_air"]},
    {"name": "DKA", "airlines": ["rano_air"]},
    {"name": "LGW", "airlines": ["air_peace"]},
    {"name": "MIU", "airlines": ["air_peace", "rano_air"]},
    {"name": "MDI", "airlines": ["air_peace", "max_air"]},
    {"name": "MED", "airlines": []},
    {"name": "ROB", "airlines": ["air_peace"]},
    {
        "name": "QOW",
        "airlines": ["air_peace", "green_africa", "max_air", "united_nigeria"],
    },
    {
        "name": "PHC",
        "airlines": [
            "air_peace",
            "green_africa",
            "ibom_air",
            "ng_eagle",
            "united_nigeria",
        ],
    },
    {
        "name": "SKO",
        "airlines": ["max_air", "ng_eagle", "rano_air", "united_nigeria"],
    },
    {"name": "QUO", "airlines": ["air_peace", "ibom_air"]},
    {"name": "QRW", "airlines": ["air_peace"]},
    {"name": "YOL", "airlines": ["air_peace", "max_air", "ng_eagle"]},
    {"name": "BIA", "airlines": ["united_nigeria"]},
]
