DOUALA = [
    {"name": "ABJ", "airlines": ["air_peace"]},
    {"name": "ABV", "airlines": ["air_peace"]},
    {"name": "ACC", "airlines": ["air_peace"]},
    {"name": "AKR", "airlines": ["air_peace"]},
    {"name": "ANA", "airlines": ["air_peace"]},
    {"name": "ABB", "airlines": ["air_peace"]},
    {"name": "BNI", "airlines": ["air_peace"]},
    {"name": "CBQ", "airlines": ["air_peace"]},
    {"name": "ENU", "airlines": ["air_peace"]},
    {"name": "GMO", "airlines": ["air_peace"]},
    {"name": "LOS", "airlines": ["air_peace", "ibom_air"]},
    {"name": "QOW", "airlines": ["air_peace"]},
    {"name": "PHC", "airlines": ["air_peace"]},
    {"name": "QUO", "airlines": ["air_peace"]},
    {"name": "QRW", "airlines": ["air_peace"]},
    {"name": "YOL", "airlines": ["air_peace"]},
]

DAKAR = [
    {"name": "ABJ", "airlines": ["air_peace"]},
    {"name": "ABV", "airlines": ["air_peace"]},
    {"name": "ACC", "airlines": ["air_peace"]},
    {"name": "BJL", "airlines": ["air_peace"]},
    {"name": "ANA", "airlines": ["air_peace"]},
    {"name": "BNI", "airlines": ["air_peace"]},
    {"name": "ILR", "airlines": ["air_peace"]},
    {"name": "GMO", "airlines": ["air_peace"]},
    {"name": "LOS", "airlines": ["air_peace", "ibom_air"]},
    {"name": "QOW", "airlines": ["air_peace"]},
    {"name": "JED", "airlines": ["air_peace"]},
    {"name": "YOL", "airlines": ["air_peace"]},
]

FREETOWN = [
    {"name": "ABV", "airlines": ["air_peace"]},
    {"name": "ACC", "airlines": ["air_peace"]},
    {"name": "AKR", "airlines": ["air_peace"]},
    {"name": "ANA", "airlines": ["air_peace"]},
    {"name": "ABB", "airlines": ["air_peace"]},
    {"name": "BNI", "airlines": ["air_peace"]},
    {"name": "CBQ", "airlines": ["air_peace"]},
    {"name": "ILR", "airlines": ["air_peace"]},
    {"name": "GMO", "airlines": ["air_peace"]},
    {"name": "LOS", "airlines": ["air_peace", "ibom_air"]},
    {"name": "QOW", "airlines": ["air_peace"]},
    {"name": "KAD", "airlines": ["air_peace"]},
    {"name": "MIU", "airlines": ["air_peace"]},
    {"name": "QUO", "airlines": ["air_peace"]},
    {"name": "QRW", "airlines": ["air_peace"]},
    {"name": "YOL", "airlines": ["air_peace"]},
]
