LONDON = [
    {"name": "ABJ", "airlines": ["air_peace"]},
    {
        "name": "ABV",
        "airlines": ["air_peace"],
    },
    {"name": "ACC", "airlines": ["air_peace"]},
    {"name": "AKR", "airlines": ["air_peace"]},
    {"name": "ANA", "airlines": ["air_peace"]},
    {"name": "ABB", "airlines": ["air_peace"]},
    {"name": "BJL", "airlines": ["air_peace"]},
    {"name": "BCU", "airlines": []},
    {
        "name": "BNI",
        "airlines": ["air_peace"],
    },
    {"name": "DNBK", "airlines": []},
    {"name": "CBQ", "airlines": ["air_peace"]},
    {"name": "COO", "airlines": ["air_peace"]},
    {"name": "DSS", "airlines": ["air_peace"]},
    {"name": "DLA", "airlines": ["air_peace"]},
    {"name": "FNA", "airlines": ["air_peace"]},
    {
        "name": "ENU",
        "airlines": ["air_peace"],
    },
    {"name": "GMO", "airlines": ["air_peace"]},
    {"name": "IBA", "airlines": []},
    {"name": "ILR", "airlines": ["air_peace"]},
    {"name": "JED", "airlines": ["air_peace"]},
    {"name": "JOS", "airlines": []},
    {"name": "JNB", "airlines": ["air_peace"]},
    {
        "name": "KAN",
        "airlines": ["air_peace"],
    },
    {"name": "KAD", "airlines": ["air_peace"]},
    {"name": "DKA", "airlines": []},
    {"name": "LOS", "airlines": ["air_peace"]},
    {"name": "MIU", "airlines": ["air_peace"]},
    {"name": "MDI", "airlines": ["air_peace"]},
    {"name": "MED", "airlines": []},
    {"name": "ROB", "airlines": ["air_peace"]},
    {"name": "QOW", "airlines": ["air_peace"]},
    {
        "name": "PHC",
        "airlines": ["air_peace"],
    },
    {"name": "SKO", "airlines": []},
    {"name": "QUO", "airlines": ["air_peace"]},
    {"name": "QRW", "airlines": ["air_peace"]},
    {"name": "YOL", "airlines": ["air_peace"]},
]
